name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "TAG=$(date +%s)" >> $GITHUB_ENV
    - run: echo $TAG
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file sample-packages/docker/Dockerfile --tag ghcr.io/kubino148/excercise_image:$TAG
    - name: login to GH Package repo
      run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
    - name: push docker image to GH repo 
      run: docker push ghcr.io/kubino148/excercise_image:$TAG
